package model;

import java.util.UUID;

import model.common.AppModule;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import java.util.UUID;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 10 11:11:19 CEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    public void methodToThrowException() {
        
        throw new JboException("Faild to Load");
    }

    /**
     * Container's getter for SavepointTableView1.
     * @return SavepointTableView1
     */
    public ViewObjectImpl getSavepointTableView1() {
        return (ViewObjectImpl) findViewObject("SavepointTableView1");
    }
}

