package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 10 11:18:59 CEST 2023
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void methodToThrowException();
}

